import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import Navbar from "./components/Navbar";

const antonRegular = localFont({
  src: "/fonts/Anton/Anton-Regular.ttf",
});

const robotoRegular = localFont({
  src: "/fonts/Roboto/Roboto-Regular.ttf"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Guitar Habit Music Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoRegular.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
