import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import Navbar from "./components/Navbar";

const antonRegular = localFont({
  src: "/fonts/Anton/Anton-Regular.ttf",
  variable: "--font-heading",
});

const robotoRegular = localFont({
  src: "/fonts/Roboto/Roboto-Regular.ttf"
});

const yellowtailRegular = localFont({
  src: "/fonts/Yellowtail/Yellowtail-Regular.ttf",
  variable: "--font-yellowtail",
})

const rethinkSans = localFont({
  src: "/fonts/Rethink/RethinkSans.ttf",
  variable: "--font-rethink",
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Guitar Habit Music Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='scroll-smooth scroll-pt-50' style={{scrollBehavior:'smooth',}}>
      <body
        className={`${robotoRegular.className} ${antonRegular.variable} 
        ${yellowtailRegular.variable} ${rethinkSans.variable}
        antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
